// <auto-generated />
using System;
using Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(SDPSContext))]
    partial class SDPSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TaxRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "EUR",
                            DocumentNumber = "INV-111",
                            DocumentType = "Invoice",
                            DueDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Uploaded",
                            Subtotal = 246m,
                            SupplierName = "Company X",
                            Tax = 41.82m,
                            TaxRate = 0.17m,
                            Total = 287.82m
                        },
                        new
                        {
                            Id = 2,
                            Currency = "BAM",
                            DocumentNumber = "INV-222",
                            DocumentType = "Invoice",
                            DueDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Uploaded",
                            Subtotal = 645m,
                            SupplierName = "Company 0",
                            Tax = 129m,
                            TaxRate = 0.2m,
                            Total = 774m
                        },
                        new
                        {
                            Id = 3,
                            Currency = "BAM",
                            DocumentNumber = "INV-333",
                            DocumentType = "Purchase Order",
                            IssueDate = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Uploaded",
                            Subtotal = 213m,
                            SupplierName = "Buyer 0",
                            Tax = 7m,
                            TaxRate = 0.5m,
                            Total = 9m
                        },
                        new
                        {
                            Id = 4,
                            Currency = "EUR",
                            DueDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Uploaded",
                            Subtotal = 645m,
                            Tax = 129m,
                            TaxRate = 0.2m,
                            Total = 774m
                        });
                });

            modelBuilder.Entity("Database.Entities.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("LineItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Item1",
                            DocumentId = 1,
                            Quantity = 1,
                            Total = 78m,
                            UnitPrice = 78m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Item2",
                            DocumentId = 1,
                            Quantity = 2,
                            Total = 168m,
                            UnitPrice = 84m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Service A",
                            DocumentId = 2,
                            Quantity = 5,
                            Total = 645m,
                            UnitPrice = 129m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Service B",
                            DocumentId = 3,
                            Quantity = 3,
                            Total = 204m,
                            UnitPrice = 96m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Service C",
                            DocumentId = 4,
                            Quantity = 5,
                            Total = 645m,
                            UnitPrice = 129m
                        });
                });

            modelBuilder.Entity("Database.Entities.LineItem", b =>
                {
                    b.HasOne("Database.Entities.Document", "Document")
                        .WithMany("LineItems")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Database.Entities.Document", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
